"""Per-user report cover backgrounds, generated by Số chủ đạo and cached.

Design (P4):
  - Cache key = Số chủ đạo (1-9, 11, 22) → at most ~11 generated files, reused
    across every paid report sharing that number (cheap, near-static once warm).
  - Generation is best-effort: timeout-bounded, atomic write, per-key lock to
    avoid double-gen under concurrency.
  - FAIL-SAFE: any error/timeout/missing-key → static fallback cover → None.
    This function NEVER raises, so it can never block a paid fulfillment.
"""

from __future__ import annotations

import asyncio
import logging
import os
import uuid
from pathlib import Path

from app.config import settings
from app.services.image_gen import generate_image_bytes, is_configured, optimize_image
from app.services.report_art_prompts import build_cover_prompt
from app.services.report_assets import cover_fallback

logger = logging.getLogger(__name__)

_TIMEOUT_S = float(os.environ.get("COVER_GEN_TIMEOUT", "20"))
_MAX_PX = 1240  # cover long-edge cap (keeps PDF size reasonable)
_COVER_DIR = Path(settings.media_root) / "covers"

# Per-key locks so two concurrent orders with the same Số chủ đạo don't both gen.
_locks: dict[int, asyncio.Lock] = {}


def _lock_for(n: int) -> asyncio.Lock:
    lock = _locks.get(n)
    if lock is None:
        lock = _locks[n] = asyncio.Lock()
    return lock


def _cached(n: int) -> Path:
    return _COVER_DIR / f"{n}.jpg"


async def get_cover_background(so_chu_dao: int) -> str | None:
    """Return a cover-background URL for a Số chủ đạo (cache-first), else fallback.

    Returns a ``file://`` URL for a generated/cached cover, a relative path for
    the static fallback, or None. Never raises.
    """
    try:
        cached = _cached(so_chu_dao)
        if cached.exists():
            return cached.resolve().as_uri()

        async with _lock_for(so_chu_dao):
            if cached.exists():  # another task generated it while we waited
                return cached.resolve().as_uri()

            if not is_configured():
                logger.info("cover gen skipped (no image-gen auth) — using static fallback")
                return cover_fallback()

            raw = await asyncio.wait_for(
                asyncio.to_thread(
                    generate_image_bytes, build_cover_prompt(so_chu_dao), "3:4",
                ),
                timeout=_TIMEOUT_S,
            )
            img = optimize_image(raw, _MAX_PX)

            _COVER_DIR.mkdir(parents=True, exist_ok=True)
            tmp = _COVER_DIR / f".{so_chu_dao}.{uuid.uuid4().hex}.tmp"
            tmp.write_bytes(img)
            os.replace(tmp, cached)  # atomic publish
            logger.info("generated per-user cover for so_chu_dao=%s", so_chu_dao)
            return cached.resolve().as_uri()

    except Exception as exc:  # noqa: BLE001 — fail-safe: never block fulfillment
        logger.warning(
            "cover gen failed (so_chu_dao=%s): %s — using static fallback",
            so_chu_dao, exc,
        )
        return cover_fallback()
