/**
 * SePayPaymentBlock — unified SePay transfer card used by every payment flow
 * (PDF report orders + chat add-on purchases).
 *
 * Renders: status badge → highlighted ref code → bank info grid (with per-row
 * copy buttons) → amount summary → reassurance footnote.
 *
 * Caller controls polling and passes `status` so the block can morph between
 * pending / paid / expired without internal state.
 */
import {
  Building2,
  Check,
  CheckCircle2,
  Clock,
  Copy,
  Loader2,
  User,
  XCircle,
} from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

import { type BankInfo, getBankInfo } from '@/lib/payment-api'
import { cn, formatVnd } from '@/lib/utils'

export type SePayStatus = 'pending' | 'paid' | 'expired' | 'failed'

interface SePayPaymentBlockProps {
  /** Final price in VND */
  amount: number
  /** Unique transfer reference — MUST appear verbatim in the transfer content */
  refCode: string
  /** Current payment status driven by parent's polling logic */
  status: SePayStatus
  /** Optional headline overriding the default "Thông tin chuyển khoản" */
  title?: string
  /** Optional extra note below the bank info (e.g. timeout messaging) */
  footnote?: React.ReactNode
  /** Auto-poll indicator — shows spinner next to "Đang chờ thanh toán" pill */
  isPolling?: boolean
}

const STATUS_META: Record<
  SePayStatus,
  { label: string; pill: string; banner: string; icon: typeof Clock }
> = {
  pending: {
    label: 'Đang chờ thanh toán',
    pill: 'bg-warning/15 text-warning border-warning/40',
    banner: 'bg-warning/10 border-warning/30 text-foreground',
    icon: Clock,
  },
  paid: {
    label: 'Đã thanh toán',
    pill: 'bg-success/15 text-success border-success/40',
    banner: 'bg-success/10 border-success/30 text-foreground',
    icon: CheckCircle2,
  },
  expired: {
    label: 'Hết hạn',
    pill: 'bg-destructive/15 text-destructive border-destructive/40',
    banner: 'bg-destructive/10 border-destructive/30 text-foreground',
    icon: XCircle,
  },
  failed: {
    label: 'Thất bại',
    pill: 'bg-destructive/15 text-destructive border-destructive/40',
    banner: 'bg-destructive/10 border-destructive/30 text-foreground',
    icon: XCircle,
  },
}

// ---------------------------------------------------------------------------
// Copy button — generic one-tap copy with 2s "Đã sao chép" feedback.
// ---------------------------------------------------------------------------

function CopyButton({
  value,
  label = 'Sao chép',
  size = 'sm',
}: {
  value: string
  label?: string
  size?: 'sm' | 'md'
}) {
  const [copied, setCopied] = useState(false)
  const handle = async () => {
    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // ignore — clipboard blocked
    }
  }
  return (
    <button
      type="button"
      onClick={handle}
      aria-label={label}
      className={cn(
        'shrink-0 inline-flex items-center gap-1 rounded-md border transition-colors',
        size === 'sm' ? 'px-2 py-1 text-xs' : 'px-3 py-1.5 text-sm',
        copied
          ? 'border-success/40 bg-success/10 text-success'
          : 'border-border bg-card hover:border-primary/40 hover:text-primary text-muted-foreground'
      )}
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
      {copied ? 'Đã chép' : label}
    </button>
  )
}

// ---------------------------------------------------------------------------
// Field row — label left, value right (mono), copy button.
// ---------------------------------------------------------------------------

function FieldRow({
  label,
  value,
  icon: Icon,
  mono = true,
}: {
  label: string
  value: string
  icon?: typeof Building2
  mono?: boolean
}) {
  return (
    <div className="flex items-center gap-3 py-2.5 first:pt-0 last:pb-0 border-b border-border/60 last:border-0">
      <div className="flex items-center gap-2 min-w-[110px] shrink-0">
        {Icon && (
          <Icon
            className="w-3.5 h-3.5 text-muted-foreground"
            aria-hidden="true"
          />
        )}
        <span className="text-xs text-muted-foreground">{label}</span>
      </div>
      <span
        className={cn(
          'flex-1 min-w-0 truncate text-sm text-foreground',
          mono ? 'font-mono font-medium' : 'font-medium'
        )}
        title={value}
      >
        {value || '—'}
      </span>
      {value && <CopyButton value={value} />}
    </div>
  )
}

// ---------------------------------------------------------------------------
// SePayQrCode — VietQR image generated by https://qr.sepay.vn/img.
// Pure URL-based — no API key needed; the bank app reads acc/bank/amount/des
// directly from the QR payload so the user only needs to confirm the transfer.
// ---------------------------------------------------------------------------

const SEPAY_QR_BASE = 'https://qr.sepay.vn/img'

function buildSePayQrUrl(opts: {
  accountNumber: string
  bankCode: string
  amount: number
  description: string
  template?: 'compact' | 'qronly'
}): string {
  const params = new URLSearchParams({
    acc: opts.accountNumber,
    bank: opts.bankCode,
    amount: String(opts.amount),
    des: opts.description,
  })
  if (opts.template) params.set('template', opts.template)
  return `${SEPAY_QR_BASE}?${params.toString()}`
}

function SePayQrCode({
  accountNumber,
  bankCode,
  amount,
  description,
}: {
  accountNumber: string
  bankCode: string
  amount: number
  description: string
}) {
  const [loaded, setLoaded] = useState(false)
  const [failed, setFailed] = useState(false)
  const qrUrl = buildSePayQrUrl({
    accountNumber,
    bankCode,
    amount,
    description,
    template: 'compact',
  })

  return (
    <div className="rounded-xl border border-border bg-background/60 p-4 flex flex-col sm:flex-row items-center gap-4">
      <div className="relative w-44 h-44 shrink-0 rounded-lg border border-border bg-white flex items-center justify-center overflow-hidden">
        {!loaded && !failed && (
          <Loader2
            className="w-5 h-5 animate-spin text-muted-foreground"
            aria-hidden="true"
          />
        )}
        {failed ? (
          <p className="px-3 text-[11px] text-destructive text-center">
            Không tải được QR
          </p>
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={qrUrl}
            alt={`QR thanh toán ${description}`}
            className={cn(
              'w-full h-full object-contain',
              loaded ? 'opacity-100' : 'opacity-0'
            )}
            onLoad={() => setLoaded(true)}
            onError={() => setFailed(true)}
          />
        )}
      </div>
      <div className="flex-1 min-w-0 text-center sm:text-left">
        <p className="text-sm font-semibold text-foreground mb-1">
          Quét QR để thanh toán
        </p>
        <p className="text-xs text-muted-foreground leading-relaxed mb-3">
          Mở ứng dụng ngân hàng → quét mã → xác nhận. Số tiền và nội dung được
          tự động điền sẵn.
        </p>
        <a
          href={qrUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
        >
          Tải ảnh QR
        </a>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export default function SePayPaymentBlock({
  amount,
  refCode,
  status,
  title = 'Thông tin chuyển khoản',
  footnote,
  isPolling = false,
}: SePayPaymentBlockProps) {
  const [bank, setBank] = useState<BankInfo | null>(null)
  const [bankError, setBankError] = useState<string | null>(null)

  const loadBank = useCallback(() => {
    getBankInfo()
      .then(setBank)
      .catch((err) => setBankError((err as Error).message))
  }, [])

  useEffect(() => {
    loadBank()
  }, [loadBank])

  const meta = STATUS_META[status]
  const StatusIcon = meta.icon

  return (
    <div className="rounded-2xl border border-border bg-card shadow-md overflow-hidden">
      {/* Header — title + status pill */}
      <div className="px-5 py-4 border-b border-border bg-gradient-to-r from-primary/8 via-card to-card flex items-center justify-between gap-3">
        <h2 className="font-semibold text-base text-foreground flex items-center gap-2">
          <span
            aria-hidden="true"
            className="inline-block w-1.5 h-1.5 rounded-full bg-primary shadow-[0_0_8px_rgba(249,106,45,0.6)]"
          />
          {title}
        </h2>
        <span
          className={cn(
            'inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium',
            meta.pill
          )}
        >
          {status === 'pending' && isPolling ? (
            <Loader2 className="w-3 h-3 animate-spin" />
          ) : (
            <StatusIcon className="w-3 h-3" />
          )}
          {meta.label}
        </span>
      </div>

      {/* Resolved-state banner */}
      {status === 'paid' && (
        <div
          className={cn(
            'border-b border-border px-5 py-3 text-sm',
            meta.banner
          )}
        >
          <p className="font-semibold flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-success" />
            Đã nhận thanh toán — gói đang được kích hoạt.
          </p>
        </div>
      )}
      {(status === 'expired' || status === 'failed') && (
        <div
          className={cn(
            'border-b border-border px-5 py-3 text-sm',
            meta.banner
          )}
        >
          <p className="font-semibold flex items-center gap-2">
            <XCircle className="w-4 h-4 text-destructive" />
            {status === 'expired'
              ? 'Mã thanh toán đã hết hạn. Vui lòng khởi tạo lại.'
              : 'Thanh toán không thành công. Liên hệ hỗ trợ nếu cần.'}
          </p>
        </div>
      )}

      <div className="p-5 space-y-5">
        {/* SePay VietQR — scan with banking app to auto-fill account, amount and content.
            Hidden on resolved states since the QR is no longer actionable. */}
        {status === 'pending' && bank && bank.account_number && (
          <SePayQrCode
            accountNumber={bank.account_number}
            bankCode={bank.bank_code || bank.bank_name}
            amount={amount}
            description={refCode}
          />
        )}

        {/* Ref code — the single most critical field (auto-fulfillment key) */}
        <div className="rounded-xl border border-primary/40 bg-primary/5 px-4 py-3 flex items-center gap-3">
          <div className="flex-1 min-w-0">
            <p className="text-[11px] uppercase tracking-wider font-semibold text-muted-foreground/90">
              Nội dung chuyển khoản (bắt buộc)
            </p>
            <p className="text-xl sm:text-2xl font-mono font-bold tracking-wider text-primary truncate">
              {refCode}
            </p>
          </div>
          <CopyButton value={refCode} label="Chép mã" size="md" />
        </div>

        {/* Amount */}
        <div className="flex items-center justify-between gap-3 rounded-xl border border-border bg-muted/30 px-4 py-3">
          <div>
            <p className="text-[11px] uppercase tracking-wider font-semibold text-muted-foreground/90">
              Số tiền cần chuyển
            </p>
            <p className="text-2xl font-bold text-foreground tabular-nums">
              {formatVnd(amount)}
            </p>
          </div>
          <CopyButton value={String(amount)} label="Chép số tiền" />
        </div>

        {/* Bank info */}
        <div className="rounded-xl border border-border bg-background/40 px-4 py-2">
          {bankError && (
            <p className="py-3 text-xs text-destructive text-center">
              {bankError} —{' '}
              <button
                type="button"
                onClick={loadBank}
                className="underline hover:text-foreground"
              >
                thử lại
              </button>
            </p>
          )}
          {!bankError && !bank && (
            <p className="py-3 text-xs text-muted-foreground text-center inline-flex items-center justify-center gap-1.5">
              <Loader2 className="w-3 h-3 animate-spin" />
              Đang tải thông tin ngân hàng...
            </p>
          )}
          {bank && (
            <>
              <FieldRow
                label="Ngân hàng"
                value={bank.bank_name || bank.bank_code}
                icon={Building2}
                mono={false}
              />
              <FieldRow
                label="Số tài khoản"
                value={bank.account_number}
                icon={Building2}
              />
              <FieldRow
                label="Chủ tài khoản"
                value={bank.account_holder}
                icon={User}
                mono={false}
              />
            </>
          )}
        </div>

        {/* Reassurance */}
        <p className="text-xs text-muted-foreground leading-relaxed">
          ✓ Hệ thống kích hoạt tự động ngay khi nhận được tiền (thường trong vài
          phút). Chuyển đúng{' '}
          <span className="font-semibold text-foreground">số tiền</span> và{' '}
          <span className="font-semibold text-foreground">nội dung</span> ở trên
          để giao dịch khớp tự động.
        </p>

        {footnote && (
          <div className="text-xs text-muted-foreground border-t border-border pt-3">
            {footnote}
          </div>
        )}
      </div>
    </div>
  )
}
